### ISSUE TITLE
Conversion produces wrong result if scalingFactor changes from time to time

### ISSUE THREAD

**Issue by AntiTenzor** [point85/CaliperSharp#3]
I think, this is because class **UnitOfMeasure** cashes scaling to **ConversionRegistry**, isn't it?

Here is a snippet to reproduce the issue:
`
UnitOfMeasure usd_uom = sys.CreateScalarUOM(UnitType.CURRENCY, "US-Dollar", "USD", "US 'paper' dollar");
sys.RegisterUnit(usd_uom);

UnitOfMeasure usdt_uom = sys.CreateScalarUOM(UnitType.CURRENCY, "Tether", "USDT", "USD 'stable' coin");
sys.RegisterUnit(usdt_uom);

// Initial conversion rate
usdt_uom.SetConversion(0.9, usd_uom);

Quantity portfolio = new Quantity(200, usdt_uom);
Console.WriteLine("Portfolio, initial  : {0} {1}", portfolio.Amount, portfolio.UOM.Symbol);
Quantity portfolio_usd = portfolio.Convert(usd_uom);
// Here we get '180 USD' as expected
Console.WriteLine("Portfolio, USD      : {0} {1}", portfolio_usd.Amount, portfolio_usd.UOM.Symbol);

Console.WriteLine();

Console.WriteLine("Tether rallies to 1...");
usdt_uom.SetConversion(1.0, usd_uom);
portfolio_usd = portfolio.Convert(usd_uom);

// (!!!) We expect '200 USD' because 1 USDT is exactly 1 USD now, but we get '180 USD'   =(
Console.WriteLine("Portfolio, USD      : {0} {1}", portfolio_usd.Amount, portfolio_usd.UOM.Symbol);
`

**Comment by point85** [comment]
Yes, AntiTensor this behavior is a result of caching the conversion factor
to USD on the first call to SetConversion().  This can be fixed by clearing
the entire conversion cache before setting the conversion to
1.0: usdt_uom.ClearCache();  However, the real fix is to have the
SetConversion method clear the cache just for this UOM, and I will submit a
fix.  Also note that in your example, you do not need to call
sys.RegisterUnit() since this is done in sys.CreateScalarUOM().

**Comment by point85** [comment]
Fixed in release v1.1.2
